In [ ]:
import torch

ModuleNotFoundError: No module named 'torch.tensor'

In [ ]:
import torch
a=torch.tensor([8])
print(a)

tensor([8])


In [ ]:
import torch
a=torch.tensor([8,5,6])
print(a)

tensor([8, 5, 6])


In [ ]:
import torch
a=torch.tensor([8,5,6])
print(a.shape)

torch.Size([3])


In [ ]:
import torch
a=torch.tensor([8,5,6])
print(a.size)

<built-in method size of Tensor object at 0x7a5da644af80>


In [ ]:
import torch
a=torch.tensor([8,5,6])
print(a.dtype)

torch.int64


In [ ]:
import torch
a=torch.eye(8,dtype=int)
print(a)

tensor([[1, 0, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0, 0],
        [0, 0, 1, 0, 0, 0, 0, 0],
        [0, 0, 0, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 1, 0, 0, 0],
        [0, 0, 0, 0, 0, 1, 0, 0],
        [0, 0, 0, 0, 0, 0, 1, 0],
        [0, 0, 0, 0, 0, 0, 0, 1]])


In [ ]:
import torch
a=torch.ones(8,5,dtype=int)
print(a)

tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]])


In [ ]:
import tensorflow as tf
x=tf.constant([1,2,3])
print(x)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [ ]:
import torch
x=torch.tensor([1,2,3])
print(x)

tensor([1, 2, 3])


In [ ]:
import torch
x=torch.tensor([1,2,3])
print(x.shape)

torch.Size([3])


In [ ]:
import torch
x=torch.tensor([1,2,3])
print(x.size)

<built-in method size of Tensor object at 0x7f0d40dc4500>


In [ ]:
import torch
x=torch.tensor([[1,2,3],[4,5,6]])
print(x.shape)

torch.Size([2, 3])


In [ ]:
import torch
x=torch.tensor([1,2,3])
print(x*2)

tensor([2, 4, 6])


In [ ]:
import torch
x=torch.tensor([[1,2],[3,4]])
print(x.size())

torch.Size([2, 2])


In [ ]:
import torch
x=torch.tensor([10,20,30,40])
print(x.numel())

4


In [ ]:
import torch
x=torch.tensor([10,20,30,40])
print(x[1:3])

tensor([20, 30])


In [ ]:
import torch
a=torch.tensor([1,2,3])
b=torch.tensor([4,5,6])
print(a+b)

tensor([5, 7, 9])


In [ ]:
import torch
a=torch.tensor([10,20,30])
print(a.sum())

tensor(60)


In [ ]:
import torch
a=torch.tensor([10,20,30])
print(a.mean())

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [ ]:
import torch
a=torch.tensor([10,5,30,15])
print(a.max())

tensor(30)


In [ ]:
import torch
a=torch.tensor([10,5,30,15])
print(a.min())

tensor(5)


In [ ]:
import torch
a=torch.arange(12)
b=a.reshape(3,4)
print(b.shape)

torch.Size([3, 4])


In [ ]:
import torch
a=torch.tensor(["Hi"])
print(a)

ValueError: too many dimensions 'str'

In [ ]:
import torch
a=torch.tensor([3,6])
print(a)

tensor([3, 6])


In [ ]:
import torch
a=torch.tensor([3,6])
print(a)
print(a.shape)
print(a.size)

tensor([3, 6])
torch.Size([2])
<built-in method size of Tensor object at 0x786d466ebe80>


In [ ]:
import torch
a=torch.tensor([3,6])
print(a)
print(a.ndim)

tensor([3, 6])
1


In [ ]:
import torch
a=torch.eye(8,dtype=int)
print(a)

tensor([[1, 0, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0, 0],
        [0, 0, 1, 0, 0, 0, 0, 0],
        [0, 0, 0, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 1, 0, 0, 0],
        [0, 0, 0, 0, 0, 1, 0, 0],
        [0, 0, 0, 0, 0, 0, 1, 0],
        [0, 0, 0, 0, 0, 0, 0, 1]])


In [ ]:
import torch
a=torch.eye(3)
print(a)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [ ]:
import torch
a=torch.full((4,3),(3))
print(a)

tensor([[3, 3, 3],
        [3, 3, 3],
        [3, 3, 3],
        [3, 3, 3]])


In [ ]:
import torch
a=torch.empty(4)
print(a)

tensor([0.0000e+00, 1.6255e-43, 7.7052e+31, 1.9447e+31])


In [ ]:
import torch
a=torch.empty(4,3)
print(a)

tensor([[3.5232e-30, 0.0000e+00, 9.1659e-31],
        [0.0000e+00, 1.1210e-43, 0.0000e+00],
        [8.9683e-44, 0.0000e+00, 3.5195e-30],
        [0.0000e+00, 1.1351e-43, 0.0000e+00]])


In [ ]:
import torch
a=torch.arange((6,19,3),dtype=int)
print(a)

TypeError: arange() received an invalid combination of arguments - got (tuple, dtype=type), but expected one of:
 * (Number end, *, Tensor out = None, torch.dtype dtype = None, torch.layout layout = None, torch.device device = None, bool pin_memory = False, bool requires_grad = False)
 * (Number start, Number end, *, torch.dtype dtype = None, torch.layout layout = None, torch.device device = None, bool pin_memory = False, bool requires_grad = False)
 * (Number start, Number end, Number step = 1, *, Tensor out = None, torch.dtype dtype = None, torch.layout layout = None, torch.device device = None, bool pin_memory = False, bool requires_grad = False)


In [ ]:
import torch
a=torch.tensor([1,2,3,4])
print(a)

tensor([1, 2, 3, 4])


In [ ]:
import torch
a=torch.tensor([1,2,3,4.5])
print(a)

tensor([1.0000, 2.0000, 3.0000, 4.5000])


In [ ]:
import torch
a=torch.tensor([1,2,3,4.5])
print(a.numel())

4


In [ ]:
import torch
a=torch.tensor([[1,2,3,4],[5,6,7,8]])
print(a)

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])


In [ ]:
import torch
a=torch.tensor([[1,2,3,4],[5,6,7,8]])
print(a[1][2])

tensor(7)


In [ ]:
import torch
a=torch.tensor([[[1,1,1,1],[1,2,3,4]],[[1,3,4,5],[1,2,3,4]]])
print(a)


tensor([[[1, 1, 1, 1],
         [1, 2, 3, 4]],

        [[1, 3, 4, 5],
         [1, 2, 3, 4]]])


In [ ]:
import torch
a=torch.tensor([8,5,4,3])
print(a[2:3])

tensor([4])


In [ ]:
import torch
a=torch.tensor([8,5,4,3])
print(a[1:4])

tensor([5, 4, 3])


In [ ]:
import torch
a=torch.tensor([8,5,4,3])
print(a[:])

tensor([8, 5, 4, 3])


In [ ]:
import torch
a=torch.tensor([[6,8,14],[7,14,18]])
print(a[:])

tensor([[ 6,  8, 14],
        [ 7, 14, 18]])


In [ ]:
import torch
a=torch.tensor([[6,8,14],[7,14,18]])
print(a[1:2,1:2])

tensor([[14]])


In [ ]:
import torch
a=torch.tensor([[6,8,14],[7,14,18],[16,5,4]])
print(a[1:2,1:2])

tensor([[14]])


In [ ]:
import torch
a=torch.tensor([[6,8,14],[7,14,18],[16,5,4]])
print(a[1:2])

tensor([[ 7, 14, 18]])


In [ ]:
import torch
a=torch.tensor([[6,8,14],[7,14,18],[16,5,4]])
print(a[2:3,2:3])

tensor([[4]])


In [ ]:
import torch
a=torch.tensor([10,25,36,48])
print(a[2:3])

tensor([36])


In [ ]:
import torch
a=torch.tensor([10,25,36,48])
print(a[1:4])

tensor([25, 36, 48])


In [ ]:
import torch
a=torch.tensor([10,25,36,48])
print(a[2:3])

tensor([36])


In [ ]:
import torch
a=torch.tensor([[6,8,14],[7,14,18],[16,5,4]])
print(a[2:3,1:2])

tensor([[5]])


In [ ]:
import torch
a=torch.tensor([[6,8,14],[7,14,18],[16,5,4]])
print(a[2:3])

tensor([[16,  5,  4]])


In [ ]:
import torch
a=torch.tensor([[6,8,14],[7,14,18],[16,5,4]])
print(a[0:4])

tensor([[ 6,  8, 14],
        [ 7, 14, 18],
        [16,  5,  4]])


In [ ]:
import torch
a=torch.tensor([[6,8,14],[7,14,18],[16,5,4]])
print(a[1:3])

tensor([[ 7, 14, 18],
        [16,  5,  4]])


In [ ]:
import torch
a=torch.tensor([[6,8,14],[7,14,18],[16,5,4]])
print(a[0:3])

tensor([[ 6,  8, 14],
        [ 7, 14, 18],
        [16,  5,  4]])


In [ ]:
import torch
a=torch.tensor([[1,8],[7,4]])
b=torch.tensor([[1,8],[3,4]])
print(b)
print(a)

tensor([[1, 8],
        [3, 4]])
tensor([[1, 8],
        [7, 4]])


In [ ]:
import torch
a=torch.tensor([[1,8],[7,4]])
b=torch.tensor([[1,8],[3,4]])
c=torch.cat((a,b),dim=1)
print(c)

tensor([[1, 8, 1, 8],
        [7, 4, 3, 4]])


In [ ]:
import torch
a=torch.tensor([[1,8],[7,4]])
b=torch.tensor([[1,8],[3,4]])
c=torch.cat((a,b),dim=0)
print(c)

tensor([[1, 8],
        [7, 4],
        [1, 8],
        [3, 4]])


In [ ]:
import torch
a=torch.ones((5,4),dtype=int)
print(a)

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])


In [ ]:
import torch
a=torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [ ]:
import torch
a=torch.zeros(5)
print(a)

tensor([0., 0., 0., 0., 0.])


In [ ]:
import torch
a=torch.zeros(5,6,4)
print(a)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


In [ ]:
import torch
a=torch.zeros(5,4,dtype=int)
print(a)

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])


In [ ]:
import torch
a=torch.zeros(8,6,5)
print(a)

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]

In [ ]:
import torch
a=torch.tensor([1,2,3,4,5,6,7,8])
print(a)

tensor([1, 2, 3, 4, 5, 6, 7, 8])


In [ ]:
import torch
a=torch.tensor([1,2,3,4,5,6,7,8])
print(a)
print(a.reshape(4,2))
print(a.reshape(2,4))
print(a.reshape(1,8))
print(a.reshape(8,1))

tensor([1, 2, 3, 4, 5, 6, 7, 8])
tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
tensor([[1, 2, 3, 4, 5, 6, 7, 8]])
tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8]])


In [ ]:
import torch
a=torch.tensor([[1,2,3],[4,5,6]])
print(a.shape)

torch.Size([2, 3])


In [ ]:
import torch
a=torch.tensor([[1,2,3],[4,5,6]])
print(a)
print(a.reshape(2,-1))

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 2, 3],
        [4, 5, 6]])


In [ ]:
import torch
a=torch.tensor([[1,2,3],[4,5,6]])
print(a)
print(a.reshape(-1,3))
print(a.shape)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])


In [ ]:
import torch
a=torch.tensor([[1,8,4,6],[8,4,3,1]])
b=torch.tensor([[1,2,3],[4,5,6]])
c=torch.cat((a,b),dim=1)
print(c)

tensor([[1, 8, 4, 6, 1, 2, 3],
        [8, 4, 3, 1, 4, 5, 6]])


In [ ]:
import torch
a=torch.tensor([[1,8,4,6],[8,4,3,1]])
b=torch.tensor([[1,2],[4,5]])
c=torch.cat((a,b),dim=1)
print(c)

tensor([[1, 8, 4, 6, 1, 2],
        [8, 4, 3, 1, 4, 5]])


In [ ]:
import torch
a=torch.tensor([8,2,8,6,5,6,3,2,1])
b=torch.split(a,3)
print(b)

(tensor([8, 2, 8]), tensor([6, 5, 6]), tensor([3, 2, 1]))


In [ ]:
import torch
a=torch.tensor([8,2,8,6,5,6,3,2,1])
b=torch.split(a,(1))
print(b)

(tensor([8]), tensor([2]), tensor([8]), tensor([6]), tensor([5]), tensor([6]), tensor([3]), tensor([2]), tensor([1]))


In [ ]:
import torch
a=torch.tensor([8,2,8,6,5,6,3,2,1])
b=torch.split(a,(2))
print(b)

(tensor([8, 2]), tensor([8, 6]), tensor([5, 6]), tensor([3, 2]), tensor([1]))


In [ ]:
import torch
a=torch.tensor([8,2,8,6,5,6,3,2,1])
b=torch.chunk(a,3)
print(b)

(tensor([8, 2, 8]), tensor([6, 5, 6]), tensor([3, 2, 1]))


In [ ]:
import torch
a=torch.tensor([8,2,8,6,5,6,3,2,1])
b=torch.chunk(a,5)
print(b)

(tensor([8, 2]), tensor([8, 6]), tensor([5, 6]), tensor([3, 2]), tensor([1]))


In [ ]:
import torch
a=torch.tensor([8,2,8,6,5,6,3,2,1])
b=torch.split(a,(5))
print(b)

(tensor([8, 2, 8, 6, 5]), tensor([6, 3, 2, 1]))


In [ ]:
import torch
a=torch.arange(20)
print(a)
b=torch.split(a,8)
print(b)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])
(tensor([0, 1, 2, 3, 4, 5, 6, 7]), tensor([ 8,  9, 10, 11, 12, 13, 14, 15]), tensor([16, 17, 18, 19]))


In [ ]:
import torch
a=torch.arange(20)
print(a)
b=torch.chunk(a,8)
print(b)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])
(tensor([0, 1, 2]), tensor([3, 4, 5]), tensor([6, 7, 8]), tensor([ 9, 10, 11]), tensor([12, 13, 14]), tensor([15, 16, 17]), tensor([18, 19]))


In [ ]:
import torch
a=torch.arange(20)
print(a)
b=torch.split(a,1)
print(b)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])
(tensor([0]), tensor([1]), tensor([2]), tensor([3]), tensor([4]), tensor([5]), tensor([6]), tensor([7]), tensor([8]), tensor([9]), tensor([10]), tensor([11]), tensor([12]), tensor([13]), tensor([14]), tensor([15]), tensor([16]), tensor([17]), tensor([18]), tensor([19]))


In [ ]:
import torch
a=torch.arange(20)
print(a)
b=torch.split(a,5)
print(b)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])
(tensor([0, 1, 2, 3, 4]), tensor([5, 6, 7, 8, 9]), tensor([10, 11, 12, 13, 14]), tensor([15, 16, 17, 18, 19]))


In [ ]:
import torch
a=torch.arange(20)
print(a)
b=torch.chunk(a,1)
print(b)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])
(tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19]),)


In [ ]:
import torch
a=torch.arange(20)
print(a)
b=torch.split(a,2)
print(b)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])
(tensor([0, 1]), tensor([2, 3]), tensor([4, 5]), tensor([6, 7]), tensor([8, 9]), tensor([10, 11]), tensor([12, 13]), tensor([14, 15]), tensor([16, 17]), tensor([18, 19]))


In [ ]:
import torch
a=torch.arange(20)
print(a)
b=torch.chunk(a,2)
print(b)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])
(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), tensor([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]))


In [ ]:
import torch
a=torch.tensor([8,7,6,4])
b=torch.tensor([4,8,7,9])
c=a+b
print(c)

tensor([12, 15, 13, 13])


In [ ]:
import torch
a=torch.tensor([8,7,6,4])
b=torch.tensor([4,8,7,9])
c=torch.sum(a,b)
print(c)

TypeError: sum() received an invalid combination of arguments - got (Tensor, Tensor), but expected one of:
 * (Tensor input, *, torch.dtype dtype = None)
 * (Tensor input, tuple of ints dim, bool keepdim = False, *, torch.dtype dtype = None, Tensor out = None)
 * (Tensor input, tuple of names dim, bool keepdim = False, *, torch.dtype dtype = None, Tensor out = None)


In [ ]:
import torch
a=torch.tensor([87,56,83])
d=a.sum()
print(d)

tensor(226)


In [ ]:
import torch
b=torch.tensor([50,87,36])
e=b.sum()
print(e)

tensor(173)


In [ ]:
c=d+e
print(c)

tensor(399)


In [ ]:
import torch
b=torch.tensor([[10,4],[8,6],[4,3]])
c=b.sum()
print(c)

tensor(35)


In [ ]:
import torch
a=torch.tensor([[10,4],[8,6],[4,3]])
b=a.sum(dim=0)
print(b)

tensor([22, 13])


In [ ]:
import torch
a=torch.tensor([[10,4],[8,6],[4,3]])
b=a.sum(dim=1)
print(b)

tensor([14, 14,  7])


In [ ]:
import torch
b=torch.tensor([[10,4],[8,6],[4,3]])
c=b.mean(dtype=float)
print(c)

tensor(5.8333, dtype=torch.float64)


In [ ]:
import torch
a=torch.tensor([87,56,83])
d=a.sum(dtype=float)
print(d)

tensor(226., dtype=torch.float64)


In [ ]:
import torch
a=torch.tensor([87,56,83],dtype=float)
d=a.sum()
print(d)

tensor(226., dtype=torch.float64)


In [ ]:
import torch
a=torch.tensor([[4,8],[12,24],[36,48]],dtype=float)
print(a.mean())

tensor(22., dtype=torch.float64)


In [ ]:
import torch
a=torch.tensor([[4,8],[12,24],[36,48]],dtype=float)
print(a.mean(dim=0))

tensor([17.3333, 26.6667], dtype=torch.float64)


In [ ]:
import torch
a=torch.tensor([[4,8],[12,24],[36,48]],dtype=float)
print(a.mean(dim=1))

tensor([ 6., 18., 42.], dtype=torch.float64)


In [ ]:
import torch
a=torch.tensor([[4,8],[12,24],[36,48]],dtype=float)
print(a.mean(dim=(0,1)))

tensor(22., dtype=torch.float64)


In [ ]:
import torch
a=torch.tensor([[4,8],[12,24],[36,48]])
print(a.max())

tensor(48)


In [ ]:
import torch
a=torch.tensor([[4,8],[12,24],[36,48]])
print(a.min())

tensor(4)


In [ ]:
import torch
a=torch.tensor([[4,8],[12,24],[36,48]])
print(a.max(dim=0))

torch.return_types.max(
values=tensor([36, 48]),
indices=tensor([2, 2]))


In [ ]:
import torch
a=torch.tensor([[4,8],[12,24],[36,48]])
print(a.max(dim=1))

torch.return_types.max(
values=tensor([ 8, 24, 48]),
indices=tensor([1, 1, 1]))


In [ ]:
import torch
a=torch.tensor([8,24,36,48,100,106,8,6])
print(a.argmax())

tensor(5)


In [ ]:
import torch
a=torch.tensor([8,24,36,48,100,106,8,6])
print(a.argmin())

tensor(7)


In [ ]:
import torch
a=torch.tensor([[1,2],[3,4]])
b=torch.tensor([[1,2],[3,4]])
print(a*b)

tensor([[ 1,  4],
        [ 9, 16]])


In [ ]:
import torch
a=torch.tensor([[1,2],[3,4]])
b=torch.tensor([[1,2],[3,4]])
print(a@b)

tensor([[ 7, 10],
        [15, 22]])


In [ ]:
import torch
a=torch.tensor([[8,4,3],[3,4,6]])
b=torch.tensor([[8,9,6,7],[1,2,3,4],[6,8,5,4]])
print(a@b)

tensor([[ 86, 104,  75,  84],
        [ 64,  83,  60,  61]])


In [ ]:
import torch
a=torch.tensor([[8,4,3],[3,4,6]])
b=torch.tensor([[8,9,6,7],[1,2,3,4],[6,8,5,4]])
print(a@b)

tensor([[ 86, 104,  75,  84],
        [ 64,  83,  60,  61]])


In [ ]:
import torch
a=torch.tensor([[8,4,3],[3,4,6]])
print(a.shape)
print(a.T)
a.shape

torch.Size([2, 3])
tensor([[8, 3],
        [4, 4],
        [3, 6]])


torch.Size([2, 3])

In [ ]:
import torch
a=torch.tensor([[[8,4,3],[3,4,6]],[[1,2,3],[4,5,6]]])
print(a)

tensor([[[8, 4, 3],
         [3, 4, 6]],

        [[1, 2, 3],
         [4, 5, 6]]])


In [ ]:
import torch
a=torch.tensor([[[8,4,3],[3,4,6]],[[1,2,3],[4,5,6]]])
print(a.ndim)

3


In [ ]:
import torch
a=torch.tensor([[[8,4,3],[3,4,6]],[[1,2,3],[4,5,6]]])
print(a.shape)

torch.Size([2, 2, 3])


In [ ]:
import torch
a=torch.tensor([[[8,4,3],[3,4,6]],[[1,2,3],[4,5,6]]])
print(a.shape)

torch.Size([2, 2, 3])


In [ ]:
import torch
a=torch.tensor([[[8,4,3],[3,4,6]],[[1,2,3],[4,5,6]]])
print(a.reshape(2,6))


tensor([[8, 4, 3, 3, 4, 6],
        [1, 2, 3, 4, 5, 6]])


In [ ]:
import torch
a=torch.tensor([[[8,4,3],[3,4,6]],[[1,2,3],[4,5,6]]])
print(a.reshape(2,6))
print(a.reshape(6,2))
print(a.reshape(3,4))
print(a.reshape(4,3))
print(a.reshape(12,1))
print(a.reshape(1,12))

tensor([[8, 4, 3, 3, 4, 6],
        [1, 2, 3, 4, 5, 6]])
tensor([[8, 4],
        [3, 3],
        [4, 6],
        [1, 2],
        [3, 4],
        [5, 6]])
tensor([[8, 4, 3, 3],
        [4, 6, 1, 2],
        [3, 4, 5, 6]])
tensor([[8, 4, 3],
        [3, 4, 6],
        [1, 2, 3],
        [4, 5, 6]])
tensor([[8],
        [4],
        [3],
        [3],
        [4],
        [6],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6]])
tensor([[8, 4, 3, 3, 4, 6, 1, 2, 3, 4, 5, 6]])


In [ ]:
import tensorflow as tf
a=tf.constant([1,2,3])
print(a)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [ ]:
import tensorflow as tf
a=tf.Variable([1,2,3])
print(a)

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>


In [ ]:
import tensorflow as tf
tf.__version__

'2.20.0'

In [ ]:
import tensorflow as tf
a=tf.constant([6])
print(a)

tf.Tensor([6], shape=(1,), dtype=int32)


In [ ]:
import tensorflow as tf
a=tf.constant([1,2,3])
print(a)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [ ]:
import tensorflow as tf
a=tf.constant([0])
print(a)

tf.Tensor([0], shape=(1,), dtype=int32)


In [ ]:
import tensorflow as tf
print(tf.constant([1,2,3]))


tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [ ]:
import tensorflow as tf
a=tf.constant([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(a)

tf.Tensor(
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]], shape=(2, 2, 3), dtype=int32)


In [ ]:
import tensorflow as tf
a=tf.Variable([1,2,3])
print(a)

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>


In [ ]:
import tensorflow as tf
a=tf.Variable([1,2,3])
print(a)
b=a.assign([4,6,7])
print("After modify:",b)

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>
After modify: <tf.Variable 'UnreadVariable' shape=(3,) dtype=int32, numpy=array([4, 6, 7], dtype=int32)>


In [ ]:
import tensorflow as tf
a=tf.Variable([1,2,3])
print(a)
b=a.assign([4,6,7])
print(b)

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>
<tf.Variable 'UnreadVariable' shape=(3,) dtype=int32, numpy=array([4, 6, 7], dtype=int32)>


In [ ]:
import tensorflow as tf
a=tf.constant((0))
print(a)

tf.Tensor(0, shape=(), dtype=int32)


In [ ]:
import tensorflow as tf
a=tf.constant((1,2,3))
print(a)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [ ]:
import tensorflow as tf
a=tf.ones([2,2])
print(a)

tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)


In [ ]:
import tensorflow as tf
a=tf.ones([3,3])
print(a)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


In [ ]:
import tensorflow as tf
a=tf.zeros([2,3])
print(a)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


In [ ]:
import tensorflow as tf
a=tf.fill([3,3],(316))
print(a)

tf.Tensor(
[[316 316 316]
 [316 316 316]
 [316 316 316]], shape=(3, 3), dtype=int32)


In [ ]:
import tensorflow as tf
a=tf.fill([3,3],("joe"))
print(a)

tf.Tensor(
[[b'joe' b'joe' b'joe']
 [b'joe' b'joe' b'joe']
 [b'joe' b'joe' b'joe']], shape=(3, 3), dtype=string)


In [ ]:
import tensorflow as tf
a=tf.range(4,14,3)
print(a)

tf.Tensor([ 4  7 10 13], shape=(4,), dtype=int32)


In [ ]:
import tensorflow as tf
a=tf.Variable([[4,14,3,5],[3,4,5,6]])
print(a)

<tf.Variable 'Variable:0' shape=(2, 4) dtype=int32, numpy=
array([[ 4, 14,  3,  5],
       [ 3,  4,  5,  6]], dtype=int32)>


In [ ]:
import tensorflow as tf
a=tf.Variable([[4,14,3,5],[3,4,5,6]])
print(a)
print(a.shape)

<tf.Variable 'Variable:0' shape=(2, 4) dtype=int32, numpy=
array([[ 4, 14,  3,  5],
       [ 3,  4,  5,  6]], dtype=int32)>
(2, 4)


In [ ]:
import tensorflow as tf
a=tf.Variable([[4,14,3,5],[3,4,5,6]])
print(a)
print(tf.size(a))

<tf.Variable 'Variable:0' shape=(2, 4) dtype=int32, numpy=
array([[ 4, 14,  3,  5],
       [ 3,  4,  5,  6]], dtype=int32)>
tf.Tensor(8, shape=(), dtype=int32)


In [ ]:
import tensorflow as tf
a=tf.Variable([[4,14,3,5],[3,4,5,6]])
print(a)

<tf.Variable 'Variable:0' shape=(2, 4) dtype=int32, numpy=
array([[ 4, 14,  3,  5],
       [ 3,  4,  5,  6]], dtype=int32)>


In [ ]:
import tensorflow as tf
a=tf.Variable([[4,14,3,5],[3,4,5,6]])
print(a)
print(a.dtype)

<tf.Variable 'Variable:0' shape=(2, 4) dtype=int32, numpy=
array([[ 4, 14,  3,  5],
       [ 3,  4,  5,  6]], dtype=int32)>
<dtype: 'int32'>


In [ ]:
import tensorflow as tf
a=tf.Variable([[4,14,3,5],[3,4,5,6]])
print(a)
print(type(a))

<tf.Variable 'Variable:0' shape=(2, 4) dtype=int32, numpy=
array([[ 4, 14,  3,  5],
       [ 3,  4,  5,  6]], dtype=int32)>
<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>


In [ ]:
import tensorflow as tf
a=tf.constant([[4,14,3,5],[3,4,5,6]])
print(a.ndim)

2


In [ ]:
import tensorflow as tf
a=tf.Variable([[4,14,3,5],[3,4,5,6]])
print(a)
print(a.ndim)

<tf.Variable 'Variable:0' shape=(2, 4) dtype=int32, numpy=
array([[ 4, 14,  3,  5],
       [ 3,  4,  5,  6]], dtype=int32)>


AttributeError: 'ResourceVariable' object has no attribute 'ndim'

In [ ]:
import tensorflow as tf
a=tf.constant([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(a)
print(a[1,1])

tf.Tensor(
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]], shape=(2, 2, 3), dtype=int32)
tf.Tensor([4 5 6], shape=(3,), dtype=int32)


In [ ]:
import tensorflow as tf
a=tf.constant([[10,20,30],[40,50,60],[70,80,90]])
print(a)
print(a[1,1])

tf.Tensor(
[[10 20 30]
 [40 50 60]
 [70 80 90]], shape=(3, 3), dtype=int32)
tf.Tensor(50, shape=(), dtype=int32)


In [ ]:
import tensorflow as tf
a=tf.constant([[10,20,30],[40,50,60],[70,80,90]])
print(a)
print(tf.transpose(a))

tf.Tensor(
[[10 20 30]
 [40 50 60]
 [70 80 90]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[10 40 70]
 [20 50 80]
 [30 60 90]], shape=(3, 3), dtype=int32)


In [ ]:
a

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]], dtype=int32)>

In [ ]:
print(a[0])

tf.Tensor([10 20 30], shape=(3,), dtype=int32)


In [ ]:
import tensorflow as tf
a=tf.constant([[10,20,30],[40,50,60],[70,80,90]])
print(a)
print(tf.transpose(a)[0])
print(a[1])

tf.Tensor(
[[10 20 30]
 [40 50 60]
 [70 80 90]], shape=(3, 3), dtype=int32)
tf.Tensor([10 40 70], shape=(3,), dtype=int32)
tf.Tensor([40 50 60], shape=(3,), dtype=int32)


In [ ]:
import tensorflow as tf
a=tf.constant([[10,20,30],[40,50,60],[70,80,90]])
print(a)
print(tf.transpose(a)[0])
print(tf.transpose(a)[1])
print(tf.transpose(a)[2])

tf.Tensor(
[[10 20 30]
 [40 50 60]
 [70 80 90]], shape=(3, 3), dtype=int32)
tf.Tensor([10 40 70], shape=(3,), dtype=int32)
tf.Tensor([20 50 80], shape=(3,), dtype=int32)
tf.Tensor([30 60 90], shape=(3,), dtype=int32)


In [ ]:
import tensorflow as tf
a=tf.constant([[10,20,30],[40,50,60],[70,80,90]])
print(a)

tf.Tensor(
[[10 20 30]
 [40 50 60]
 [70 80 90]], shape=(3, 3), dtype=int32)


In [ ]:
import tensorflow as tf
a=tf.constant([[10,20,30],[40,50,60],[70,80,90]])
print(a[1,2])

tf.Tensor(60, shape=(), dtype=int32)


In [ ]:
import tensorflow as tf
a=tf.constant([[10,20,30],[40,50,60],[70,80,90]])
print(a[:,0])

tf.Tensor([10 40 70], shape=(3,), dtype=int32)


In [ ]:
import tensorflow as tf
a=tf.constant([[10,20,30],[40,50,60],[70,80,90]])
print(a[:,2])

tf.Tensor([30 60 90], shape=(3,), dtype=int32)


In [ ]:
import tensorflow as tf
a=tf.constant([[10,20,30],[40,50,60],[70,80,90]])
print(a[2,:])

tf.Tensor([70 80 90], shape=(3,), dtype=int32)


In [ ]:
import tensorflow as tf
a=tf.constant([[10,20,30],[40,50,60],[70,80,90]])
print(a[1:2])

tf.Tensor([[40 50 60]], shape=(1, 3), dtype=int32)


In [ ]:
import tensorflow as tf
a=tf.constant([[10,20,30],[40,50,60],[70,80,90]])
print(a[1:2,0:3])

tf.Tensor([[40 50 60]], shape=(1, 3), dtype=int32)


In [ ]:
import tensorflow as tf
a=tf.constant([[10,20,30],[40,50,60],[70,80,90]])
print(a[0])

tf.Tensor([10 20 30], shape=(3,), dtype=int32)


In [ ]:
import tensorflow as tf
a=tf.constant([[10,20,30],[40,50,60],[70,80,90]])
print(a[1:3,1:3])

tf.Tensor(
[[50 60]
 [80 90]], shape=(2, 2), dtype=int32)


In [ ]:
import tensorflow as tf
a=tf.constant([[10,20,30],[40,50,60],[70,80,90]])
print(a[1:3,0:2])

tf.Tensor(
[[40 50]
 [70 80]], shape=(2, 2), dtype=int32)


In [ ]:
import tensorflow as tf
a=tf.constant([[10,20,30],[40,50,60],[70,80,90]])
print(a[:,2])

tf.Tensor([30 60 90], shape=(3,), dtype=int32)


In [ ]:
import tensorflow as tf
a=tf.constant([[10,20,30],[40,50,60],[70,80,90]])
print(a[0:3,2:3])

tf.Tensor(
[[30]
 [60]
 [90]], shape=(3, 1), dtype=int32)


In [ ]:
import tensorflow as tf
a=tf.constant([[10,20,30],[40,50,60],[70,80,90]])
print(a[0])

tf.Tensor([10 20 30], shape=(3,), dtype=int32)


In [ ]:
import tensorflow as tf
a=tf.constant([[10,20,30],[40,50,60],[70,80,90]])
print(a[1])

tf.Tensor([40 50 60], shape=(3,), dtype=int32)


In [ ]:
import tensorflow as tf
a=tf.constant([[10,20,30],[40,50,60],[70,80,90]])
print(a[2])

tf.Tensor([70 80 90], shape=(3,), dtype=int32)


In [ ]:
import tensorflow as tf
a=tf.constant([[10,20,30],[40,50,60],[70,80,90]])
print(a[0,1])

tf.Tensor(20, shape=(), dtype=int32)


In [ ]:
import tensorflow as tf
a=tf.constant([[10,20,30],[40,50,60],[70,80,90]])
print(a[0][0])

tf.Tensor(10, shape=(), dtype=int32)


In [ ]:
import tensorflow as tf
a=tf.constant([[10,20,30],[40,50,60],[70,80,90]])
print(a[0,2])

tf.Tensor(30, shape=(), dtype=int32)


In [ ]:
import tensorflow as tf
a=tf.constant([[10,20,30],[40,50,60],[70,80,90]])
print(a[0:3])

tf.Tensor(
[[10 20 30]
 [40 50 60]
 [70 80 90]], shape=(3, 3), dtype=int32)


In [ ]:
import tensorflow as tf
a=tf.constant([[10,20,30],[40,50,60],[70,80,90]])
print(a)

tf.Tensor(
[[10 20 30]
 [40 50 60]
 [70 80 90]], shape=(3, 3), dtype=int32)


In [ ]:
import tensorflow as tf
a=tf.constant([10,20,30])
b=tf.reverse(a,axis=[0])
print(b)

tf.Tensor([30 20 10], shape=(3,), dtype=int32)


In [ ]:
import tensorflow as tf
a=tf.constant([[10,20,30],[70,80,90]])
b=tf.reverse(a,axis=[0])
print(b)

tf.Tensor(
[[70 80 90]
 [10 20 30]], shape=(2, 3), dtype=int32)


In [ ]:
import tensorflow as tf
a=tf.constant([[10,20,30],[70,80,90]])
b=tf.reverse(a,axis=[1])
print(b)

tf.Tensor(
[[30 20 10]
 [90 80 70]], shape=(2, 3), dtype=int32)


In [ ]:
import tensorflow as tf
a=tf.constant([[10,20,30],[70,80,90]])
b=tf.reverse(a,axis=[0,1])
print(b)

tf.Tensor(
[[90 80 70]
 [30 20 10]], shape=(2, 3), dtype=int32)


In [ ]:
import tensorflow as tf
a=tf.constant([[10,20,30],[70,80,90]])
b=tf.reverse(a,axis=[1,0])
print(b)

tf.Tensor(
[[90 80 70]
 [30 20 10]], shape=(2, 3), dtype=int32)


In [ ]:
import tensorflow as tf
a=tf.constant([[10,20,30],[70,80,90],[110,120,130]])
b=tf.reverse(a,axis=[1])
print(b)

tf.Tensor(
[[ 30  20  10]
 [ 90  80  70]
 [130 120 110]], shape=(3, 3), dtype=int32)


In [ ]:
import tensorflow as tf
a=tf.constant([[10,20,30],[70,80,90],[110,120,130]])
b=tf.reverse(a,axis=[0])
print(b)

tf.Tensor(
[[110 120 130]
 [ 70  80  90]
 [ 10  20  30]], shape=(3, 3), dtype=int32)


In [ ]:
import tensorflow as tf
a=tf.constant([[10,20,30],[70,80,90],[110,120,130]])
b=tf.reverse(a,axis=[1,0])
print(b)

tf.Tensor(
[[130 120 110]
 [ 90  80  70]
 [ 30  20  10]], shape=(3, 3), dtype=int32)


In [ ]:
import tensorflow as tf
a=tf.constant([[10,20,30],[70,80,90],[110,120,130]])
b=tf.reshape(a,(9,1))
print(b)

tf.Tensor(
[[ 10]
 [ 20]
 [ 30]
 [ 70]
 [ 80]
 [ 90]
 [110]
 [120]
 [130]], shape=(9, 1), dtype=int32)


In [ ]:
import tensorflow as tf
a=tf.constant([[10,20,30],[70,80,90],[110,120,130]])
b=tf.reshape(a,(1,-1))
print(b)
import tensorflow as tf
a=tf.constant([[10,20,30],[70,80,90],[110,120,130]])
b=tf.reshape(a,(1,9))
print(b)

tf.Tensor([[ 10  20  30  70  80  90 110 120 130]], shape=(1, 9), dtype=int32)
tf.Tensor([[ 10  20  30  70  80  90 110 120 130]], shape=(1, 9), dtype=int32)


In [ ]:
import tensorflow as tf
a=tf.constant([[10,20,30],[70,80,90],[110,120,130]])
b=tf.reshape(a,(9,-1))
print(b)

tf.Tensor([ 10  20  30  70  80  90 110 120 130], shape=(9,), dtype=int32)


In [ ]:
import tensorflow as tf
a=tf.constant([[10,20,30],[70,80,90],[110,120,130]])
b=tf.reshape(a,(-1,1))
print(b)

tf.Tensor(
[[ 10]
 [ 20]
 [ 30]
 [ 70]
 [ 80]
 [ 90]
 [110]
 [120]
 [130]], shape=(9, 1), dtype=int32)


In [ ]:
import tensorflow as tf
a=tf.constant([1,17,25,4,30])
b=tf.constant([56,45,40,51,54])
print(tf.add(a,b))


tf.Tensor([57 62 65 55 84], shape=(5,), dtype=int32)


In [ ]:
import tensorflow as tf
a=tf.constant([1,17,25,4,30])
b=tf.constant([56,45,40,51,54])
print(tf.subtract(a,b))

tf.Tensor([-55 -28 -15 -47 -24], shape=(5,), dtype=int32)


In [ ]:
import tensorflow as tf
a=tf.constant([1,17,25,4,30])
b=tf.constant([56,45,40,51,54])
print(tf.multiply(a,b))

tf.Tensor([  56  765 1000  204 1620], shape=(5,), dtype=int32)


In [ ]:
import tensorflow as tf
a=tf.constant([1,17,25,4,30])
b=tf.constant([56,45,40,51,54])
print(tf.divide(a,b))

tf.Tensor([0.01785714 0.37777778 0.625      0.07843137 0.55555556], shape=(5,), dtype=float64)


In [ ]:
import tensorflow as tf
a=tf.constant([1,17,25,4,30])
b=tf.constant([56,45,40,51,54])
c=a/b
print(c)

tf.Tensor([0.01785714 0.37777778 0.625      0.07843137 0.55555556], shape=(5,), dtype=float64)


In [ ]:
import tensorflow as tf
a=tf.constant([1,17,25,4,30])
b=tf.constant([56,45,40,51,54])
c=a/b
print(c)

tf.Tensor([0.01785714 0.37777778 0.625      0.07843137 0.55555556], shape=(5,), dtype=float64)


In [ ]:
 import tensorflow as tf
 a=tf.constant([1,17,25,4,30])
 b=tf.constant([56,45,40,51,54])
 print(tf.reduce_sum(a))
 print(tf.reduce_sum(b))


tf.Tensor(77, shape=(), dtype=int32)
tf.Tensor(246, shape=(), dtype=int32)


In [ ]:
 import tensorflow as tf
 a=tf.constant([1,17,25,4,30])
 b=tf.constant([56,45,40,51,54])
 print(tf.reduce_mean(a))

tf.Tensor(15, shape=(), dtype=int32)


In [ ]:
 import tensorflow as tf
 a=tf.constant([[1,17,25,4,30],[56,45,40,51,54]])
 b=tf.constant([56,45,40,51,54])
 print(tf.reduce_mean(a,axis=1))
 print(tf.reduce_mean(a,axis=0))

tf.Tensor([15 49], shape=(2,), dtype=int32)
tf.Tensor([28 31 32 27 42], shape=(5,), dtype=int32)


In [ ]:
import tensorflow as tf
a=tf.constant([1,17,25,4,30])
b=tf.constant([56,45,40,51,54])
print(tf.reduce_max(a))
print(tf.reduce_min(a))
print(tf.reduce_max(b))
print(tf.reduce_min(b))

tf.Tensor(30, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(56, shape=(), dtype=int32)
tf.Tensor(40, shape=(), dtype=int32)


In [ ]:
import tensorflow as tf
a=tf.constant([[1,17,25,4,30],[56,45,40,51,54],[56,45,40,51,54]])
print(tf.reshape(a,[-1]))

tf.Tensor([ 1 17 25  4 30 56 45 40 51 54 56 45 40 51 54], shape=(15,), dtype=int32)


In [ ]:
import tensorflow as tf
a=tf.constant([100,200,300])
print(a)
print(a.shape)


tf.Tensor([100 200 300], shape=(3,), dtype=int32)
(3,)


In [ ]:
import tensorflow as tf
a=tf.constant([100,200,300])
b=tf.constant([100,200,300])
print(a)
print(b)
c=a+b
print(c)

tf.Tensor([100 200 300], shape=(3,), dtype=int32)
tf.Tensor([100 200 300], shape=(3,), dtype=int32)
tf.Tensor([200 400 600], shape=(3,), dtype=int32)


In [ ]:
import tensorflow as tf
a=tf.Variable([100,200,300])
b=tf.Variable([100,200,300])
print(a)
print(b)
c=a+b
print(c)

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([100, 200, 300], dtype=int32)>
<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([100, 200, 300], dtype=int32)>
tf.Tensor([200 400 600], shape=(3,), dtype=int32)


In [ ]:
import tensorflow as tf
a=tf.ones(4,5)
print(a)

tf.Tensor([1 1 1 1], shape=(4,), dtype=int16)


In [ ]:
import tensorflow as tf
a=tf.ones([4,5])
print(a)

tf.Tensor(
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]], shape=(4, 5), dtype=float32)


In [ ]:
import tensorflow as tf
a=tf.constant(10)
b=tf.constant(10)
c=a+b
print(c)

tf.Tensor(20, shape=(), dtype=int32)


In [ ]:
import tensorflow as tf
a=tf.zeros([5,6])
print(a)

tf.Tensor(
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]], shape=(5, 6), dtype=float32)


In [ ]:
import tensorflow as tf
a=tf.Variable([1,2,3])
print(a)
b=a.assign([4,5,6])
print(b)

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>
<tf.Variable 'UnreadVariable' shape=(3,) dtype=int32, numpy=array([4, 5, 6], dtype=int32)>


In [ ]:
import tensorflow as tf
a=tf.Variable([1,2,3])
print(a)
print(a.shape)

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>
(3,)


In [ ]:
import tensorflow as tf
a=tf.constant([[1,2],[3,4]])
print(a)
print(a.shape)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [ ]:
import tensorflow as tf
a=tf.zeros((5,6))
print(a)

tf.Tensor(
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]], shape=(5, 6), dtype=float32)


In [ ]:
import tensorflow as tf
a=tf.ones((5,6))
print(a)

tf.Tensor(
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]], shape=(5, 6), dtype=float32)


In [ ]:
import tensorflow as tf
a=tf.fill((5,6),400)
print(a)

tf.Tensor(
[[400 400 400 400 400 400]
 [400 400 400 400 400 400]
 [400 400 400 400 400 400]
 [400 400 400 400 400 400]
 [400 400 400 400 400 400]], shape=(5, 6), dtype=int32)


In [ ]:
import tensorflow as tf
a=tf.fill((5,6),"Srav")
print(a)

tf.Tensor(
[[b'Srav' b'Srav' b'Srav' b'Srav' b'Srav' b'Srav']
 [b'Srav' b'Srav' b'Srav' b'Srav' b'Srav' b'Srav']
 [b'Srav' b'Srav' b'Srav' b'Srav' b'Srav' b'Srav']
 [b'Srav' b'Srav' b'Srav' b'Srav' b'Srav' b'Srav']
 [b'Srav' b'Srav' b'Srav' b'Srav' b'Srav' b'Srav']], shape=(5, 6), dtype=string)


In [ ]:
import tensorflow as tf
a=tf.fill((5,6),"S")
print(a)

tf.Tensor(
[[b'S' b'S' b'S' b'S' b'S' b'S']
 [b'S' b'S' b'S' b'S' b'S' b'S']
 [b'S' b'S' b'S' b'S' b'S' b'S']
 [b'S' b'S' b'S' b'S' b'S' b'S']
 [b'S' b'S' b'S' b'S' b'S' b'S']], shape=(5, 6), dtype=string)


In [ ]:
import tensorflow as tf
a=tf.range(10)
print(a)

tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)


In [ ]:
import tensorflow as tf
a=tf.range(10,1,-1)
print(a)

tf.Tensor([10  9  8  7  6  5  4  3  2], shape=(9,), dtype=int32)


In [ ]:
import tensorflow as tf
a=tf.range(10)
print(a)
print(tf.reshape(a,(2,5)))
print(tf.reshape(a,(5,2)))

tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)
tf.Tensor(
[[0 1 2 3 4]
 [5 6 7 8 9]], shape=(2, 5), dtype=int32)
tf.Tensor(
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]], shape=(5, 2), dtype=int32)


In [ ]:
import tensorflow as tf
a=tf.constant([10,20,30,40,50])
print(a)
print(a[-1])
print(a[::-1])
print(a[1:4])

tf.Tensor([10 20 30 40 50], shape=(5,), dtype=int32)
tf.Tensor(50, shape=(), dtype=int32)
tf.Tensor([50 40 30 20 10], shape=(5,), dtype=int32)
tf.Tensor([20 30 40], shape=(3,), dtype=int32)


In [ ]:
import tensorflow as tf
a=tf.constant([10,20,30,40,50])
print(tf.reduce_sum(a))

tf.Tensor(150, shape=(), dtype=int32)


In [ ]:
import tensorflow as tf
a=tf.constant([10,20,30,40,50])
print(tf.reduce_max(a))

tf.Tensor(50, shape=(), dtype=int32)


In [ ]:
import tensorflow as tf
a=tf.constant([10,20,30,40,50])
print(tf.reduce_min(a))

tf.Tensor(10, shape=(), dtype=int32)


In [ ]:
import tensorflow as tf
a=tf.constant([10,20,30,40,50])
print(tf.reduce_mean(a))

tf.Tensor(30, shape=(), dtype=int32)


In [ ]:
import tensorflow as tf
a=tf.constant([10,20,30,40,50])
print(a)

tf.Tensor([10 20 30 40 50], shape=(5,), dtype=int32)


In [2]:
import tensorflow as tf
a=tf.constant([100,200,300])
print(a)

tf.Tensor([100 200 300], shape=(3,), dtype=int32)


In [2]:
import torch
torch.cuda.is_available()

True

In [1]:
import torch
torch.cuda.is_available()

False

In [6]:
import torch
a=torch.tensor([2,4,6,8])
print(a)
print(a.numel())


tensor([2, 4, 6, 8])
4


In [12]:
import torch
a=torch.tensor([2,4,6,8])
print(a)
print(a.ndim)
print(a.size())
print(a.shape)

tensor([2, 4, 6, 8])
1
torch.Size([4])
torch.Size([4])


In [13]:
import torch
a=torch.tensor([2,4,6,8])
print(a)
print(a.dtype)

tensor([2, 4, 6, 8])
torch.int64


In [14]:
import torch
a=torch.tensor([2,4,6,8])
print(a)
print(type(a))

tensor([2, 4, 6, 8])
<class 'torch.Tensor'>


In [16]:
import torch
a=torch.ones((2,3),dtype=int)
print(a)

tensor([[1, 1, 1],
        [1, 1, 1]])


In [17]:
import torch
a=torch.ones((2,3),dtype=torch.int32)
print(a)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)


In [18]:
import torch
a=torch.ones((2,3),dtype=torch.int64)
print(a)

tensor([[1, 1, 1],
        [1, 1, 1]])


In [21]:
import torch
a=torch.zeros((2,2),dtype=torch.int64)
print(a)

tensor([[0, 0],
        [0, 0]])


In [22]:
import torch
a=torch.arange(5,16,2)
print(a)

tensor([ 5,  7,  9, 11, 13, 15])


In [24]:
import torch
a=torch.range(5,16,2)
print(a)
print(a[1])

tensor([ 5.,  7.,  9., 11., 13., 15.])
tensor(7.)


/tmp/ipykernel_3254/3855195834.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  a=torch.range(5,16,2)


In [25]:
import torch
a=torch.arange(5,16,2)
print(a[1:4:2])

tensor([ 7, 11])


In [26]:
import torch
a=torch.rand(3,5)
print(a)

tensor([[0.4683, 0.2443, 0.0015, 0.3420, 0.3420],
        [0.4360, 0.0399, 0.4225, 0.2733, 0.2804],
        [0.0049, 0.1091, 0.2614, 0.0291, 0.9101]])


In [27]:
import torch
a=torch.randn(3,5)
print(a)

tensor([[ 1.4469,  0.9871,  1.0207, -0.6951, -0.6152],
        [ 0.9116, -1.0044, -0.3705, -1.0232,  1.3795],
        [ 0.6283,  1.9607, -1.0689,  0.1983,  1.6843]])


In [38]:
import torch
a=torch.full((2,3),8)
print(a)

tensor([[8, 8, 8],
        [8, 8, 8]])


In [40]:
import torch
a=torch.full((2,3),800)
print(a)

tensor([[800, 800, 800],
        [800, 800, 800]])


In [41]:
import torch
a=torch.tensor([[18,36,54,78],[36,94,72,81],[24,56,79,3],[1,2,4,5]])
print(a)
print(a[[2,3]])

tensor([[18, 36, 54, 78],
        [36, 94, 72, 81],
        [24, 56, 79,  3],
        [ 1,  2,  4,  5]])
tensor([[24, 56, 79,  3],
        [ 1,  2,  4,  5]])


In [43]:
import torch
a=torch.tensor([[18,36,54,78],[36,94,72,81],[24,56,79,3],[1,2,4,5]])
print(a[2:4])
print(a[[2,3]])

tensor([[24, 56, 79,  3],
        [ 1,  2,  4,  5]])
tensor([[24, 56, 79,  3],
        [ 1,  2,  4,  5]])


In [45]:
import torch
a=torch.tensor([[18,36,54,78],[36,94,72,81],[24,56,79,3],[1,2,4,5]])
print(a[[[2,3],2]])
print(a[[2,3]])

tensor([79,  4])
tensor([[24, 56, 79,  3],
        [ 1,  2,  4,  5]])


/tmp/ipykernel_3254/1135949183.py:3: UserWarning: Using a non-tuple sequence for multidimensional indexing is deprecated and will be changed in pytorch 2.9; use x[tuple(seq)] instead of x[seq]. In pytorch 2.9 this will be interpreted as tensor index, x[torch.tensor(seq)], which will result either in an error or a different result (Triggered internally at /pytorch/torch/csrc/autograd/python_variable_indexing.cpp:347.)
  print(a[[[2,3],2]])


In [47]:
import torch
a=torch.tensor([[18,36,54,78],[36,94,72,81],[24,56,79,3],[1,2,4,5]])
print(a)
print(a[2])

tensor([[18, 36, 54, 78],
        [36, 94, 72, 81],
        [24, 56, 79,  3],
        [ 1,  2,  4,  5]])
tensor([24, 56, 79,  3])


In [50]:
import torch
a=torch.tensor([[18,36,54,78],[36,94,72,81],[24,56,79,3],[1,2,4,5]])
print(a[[1,3]])

tensor([[36, 94, 72, 81],
        [ 1,  2,  4,  5]])


In [52]:
import torch
a=torch.tensor([[18,36,54,78],[36,94,72,81],[24,56,79,3],[1,2,4,5]])
print(a[[0,1,2],3])

tensor([78, 81,  3])


In [53]:
import torch
a=torch.tensor([[18,36,54,78],[36,94,72,81],[24,56,79,3],[1,2,4,5]])
print(a)
print(a[[0,1,2],3])

tensor([[18, 36, 54, 78],
        [36, 94, 72, 81],
        [24, 56, 79,  3],
        [ 1,  2,  4,  5]])
tensor([78, 81,  3])


In [56]:
import torch
a=torch.tensor([[18,36,54,78],[36,94,72,81],[24,56,79,3],[1,2,4,5]])
print(a)
print(a[2:3,1:2])
print(a[2:4,2:4])

tensor([[18, 36, 54, 78],
        [36, 94, 72, 81],
        [24, 56, 79,  3],
        [ 1,  2,  4,  5]])
tensor([[56]])
tensor([[79,  3],
        [ 4,  5]])


In [57]:
import torch
a=torch.tensor([[18,36,54,78],[36,94,72,81],[24,56,79,3],[1,2,4,5]])
print(a)
print(a[2:,2:4])

tensor([[18, 36, 54, 78],
        [36, 94, 72, 81],
        [24, 56, 79,  3],
        [ 1,  2,  4,  5]])
tensor([[79,  3],
        [ 4,  5]])


In [58]:
import torch
a=torch.tensor([[18,36,54,78],[36,94,72,81],[24,56,79,3],[1,2,4,5]])
print(a)
print(a[1:3,1:3])

tensor([[18, 36, 54, 78],
        [36, 94, 72, 81],
        [24, 56, 79,  3],
        [ 1,  2,  4,  5]])
tensor([[94, 72],
        [56, 79]])


In [65]:
import torch
a=torch.tensor([[18,36,54,78],[36,94,72,81],[24,56,79,3],[1,2,4,5]])
print(a)
print(a[-3:-1,-3:-1])

tensor([[18, 36, 54, 78],
        [36, 94, 72, 81],
        [24, 56, 79,  3],
        [ 1,  2,  4,  5]])
tensor([[94, 72],
        [56, 79]])


In [70]:
import torch
a=torch.tensor([[1,2,3],[4,5,6]])
b=torch.tensor([[7,8,9],[10,11,12]])
print(sum(a))
c=torch.add(a,b)
print(c)
print(a)

tensor([5, 7, 9])
tensor([[ 8, 10, 12],
        [14, 16, 18]])
tensor([[1, 2, 3],
        [4, 5, 6]])


In [71]:
import torch
a=torch.tensor([[1,2,3],[4,5,6]])
b=torch.tensor([[7,8,9],[10,11,12]])
c=torch.sub(a,b)
print(c)

tensor([[-6, -6, -6],
        [-6, -6, -6]])


In [72]:
import torch
a=torch.tensor([[1,2,3],[4,5,6]])
b=torch.tensor([[7,8,9],[10,11,12]])
c=torch.subtract(a,b)
print(c)

tensor([[-6, -6, -6],
        [-6, -6, -6]])


In [73]:
import torch
a=torch.tensor([[1,2,3],[4,5,6]])
b=torch.tensor([[7,8,9],[10,11,12]])
c=torch.mul(a,b)
print(c)

tensor([[ 7, 16, 27],
        [40, 55, 72]])


In [82]:
import torch
a=torch.tensor([[1,2],[4,5]])
b=torch.tensor([[7,8],[10,11]])

print(a@b)

tensor([[27, 30],
        [78, 87]])


In [77]:
import torch
a=torch.tensor([1,2,3,4,5,6])
print(a)
c=torch.flip(a,dims=[0])
print(c)

tensor([1, 2, 3, 4, 5, 6])
tensor([6, 5, 4, 3, 2, 1])


In [79]:
import torch
a=torch.tensor([1,2,3,4,5,6])
print(a)
c=torch.flip(a,dims=[0])
print(c)

tensor([1, 2, 3, 4, 5, 6])
tensor([6, 5, 4, 3, 2, 1])


In [80]:
import torch
a=torch.tensor([[1,2,3,4,5,6],[8,9,10,11,12,13]])
print(a)
c=torch.flip(a,dims=[1])
print(c)


tensor([[ 1,  2,  3,  4,  5,  6],
        [ 8,  9, 10, 11, 12, 13]])
tensor([[ 6,  5,  4,  3,  2,  1],
        [13, 12, 11, 10,  9,  8]])


In [85]:
import torch
a=torch.tensor([[1,2,3,4,5,6],[8,9,10,11,12,13]])
print(a)
print(a.max())
print(a.argmax())

tensor([[ 1,  2,  3,  4,  5,  6],
        [ 8,  9, 10, 11, 12, 13]])
tensor(13)
tensor(11)


In [86]:
import torch
a=torch.tensor([[1,2,3,4,5,6],[8,9,10,11,12,13]])
print(a.argmax())

tensor(11)


In [89]:
import torch
a=torch.tensor([1,2,3,4,5,6])
print(a.argmax())
print(torch.argmax(a))
print(torch.argmin(a))

tensor(5)
tensor(5)
tensor(0)


In [90]:
import torch
a=torch.tensor([1,2,3,4,5,6])
print(a.max())
print(torch.max(a))

tensor(6)
tensor(6)


In [91]:
import torch
a=torch.tensor([[18,36,54,78],[36,94,72,81],[24,56,79,3],[1,2,4,5]])
print(a)
print(a[:,0])

tensor([[18, 36, 54, 78],
        [36, 94, 72, 81],
        [24, 56, 79,  3],
        [ 1,  2,  4,  5]])
tensor([18, 36, 24,  1])


In [ ]:
import torch
ai=torch.tensor([40,60,30,70,95])
print(ai)

In [ ]:
a=[40,60,30,70,95]
print(a>60)